routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('/home');
});

Auth::routes();
Route::middleware(['auth'])->group(function () {

	Route::get('/home', 'HomeController@index')->name('home');


	Route::resource('clientes', 'clientesController');

	Route::resource('carros', 'carrosController');

	Route::resource('servicios', 'ServicioController');

	Route::get('facturas/new/{id}', 'FacturasController@new_fac');
	Route::post('facturas/new', 'FacturasController@new_storage');
	Route::resource('facturas', 'FacturasController');

});

app/Models/carros.php
<?php

namespace App\Models;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Class carros
 * @package App\Models
 * @version May 21, 2017, 9:48 pm UTC
 */
class carros extends Model
{
    use SoftDeletes;

    public $table = 'carros';
    

    protected $dates = ['deleted_at'];


    public $fillable = [
        'modelo',
        'placa',
        'cliente_id'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'modelo' => 'string',
        'placa' => 'string',
        'cliente_id' => 'integer'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        'modelo' => 'required',
        'cliente_id' => 'required'
    ];
    
    public static function boot()
    {
        parent::boot();
    
        static::deleting(function($carro) { 
             $carro->facturas()->delete();
        });
    }

    public function cliente()
    {
        return $this->belongsTo('App\Models\clientes','cliente_id');
    }

    public function facturas()
    {
        return $this->hasMany('App\Models\Facturas','carro_id');
    }

    public function getDataAttribute()
    {
        return $this->modelo . ' - Placa: ' . $this->placa;
    }
    
}

app/Http/Controllers/carrosController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreatecarrosRequest;
use App\Http\Requests\UpdatecarrosRequest;
use App\Repositories\carrosRepository;
use App\Http\Controllers\AppBaseController;
use Illuminate\Http\Request;
use Flash;
use Prettus\Repository\Criteria\RequestCriteria;
use Response;
// Models
use App\Models\carros;
use App\Models\clientes;

class carrosController extends AppBaseController
{
    /** @var  carrosRepository */
    private $carrosRepository;

    public function __construct(carrosRepository $carrosRepo)
    {
        $this->carrosRepository = $carrosRepo;
    }

    /**
     * Display a listing of the carros.
     *
     * @param Request $request
     * @return Response
     */
    public function index(Request $request)
    {
        $this->carrosRepository->pushCriteria(new RequestCriteria($request));
        $carros = $this->carrosRepository->all();

        return view('carros.index')
            ->with('carros', $carros);
    }

    /**
     * Show the form for creating a new carros.
     *
     * @return Response
     */
    public function create()
    {
        $clientes = clientes::all();
        $carros = new carros();
        return view('carros.create')
                ->with('carros',$carros)
                ->with('clientes',$clientes);
    }

    /**
     * Store a newly created carros in storage.
     *
     * @param CreatecarrosRequest $request
     *
     * @return Response
     */
    public function store(CreatecarrosRequest $request)
    {
        $input = $request->all();

        $carros = $this->carrosRepository->create($input);

        Flash::success('Carro registrado correctamente.');

        return redirect(route('carros.index'));
    }

    /**
     * Display the specified carros.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $carros = $this->carrosRepository->findWithoutFail($id);

        if (empty($carros)) {
            Flash::error('Carros not found');

            return redirect(route('carros.index'));
        }

        return view('carros.show')->with('carros', $carros);
    }

    /**
     * Show the form for editing the specified carros.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $carros = $this->carrosRepository->findWithoutFail($id);

        if (empty($carros)) {
            Flash::error('Carros not found');

            return redirect(route('carros.index'));
        }

        $clientes = clientes::all();
        return view('carros.edit')
                ->with('carros', $carros)
                ->with('clientes',$clientes);
    }

    /**
     * Update the specified carros in storage.
     *
     * @param  int              $id
     * @param UpdatecarrosRequest $request
     *
     * @return Response
     */
    public function update($id, UpdatecarrosRequest $request)
    {
        $carros = $this->carrosRepository->findWithoutFail($id);

        if (empty($carros)) {
            Flash::error('Carros not found');

            return redirect(route('carros.index'));
        }

        $carros = $this->carrosRepository->update($request->all(), $id);

        Flash::success('Carro actualizado correctamente.');

        return redirect(route('carros.index'));
    }

    /**
     * Remove the specified carros from storage.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function destroy($id)
    {
        $carros = $this->carrosRepository->findWithoutFail($id);

        if (empty($carros)) {
            Flash::error('Carros not found');

            return redirect(route('carros.index'));
        }

        $this->carrosRepository->delete($id);

        Flash::success('Carro borrado correctamente.');

        return redirect(route('carros.index'));
    }
}

resources/views/carros/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Carros
        </h1>
    </section>
    <div class="content">
        @include('adminlte-templates::common.errors')
        <div class="box box-primary">

            <div class="box-body">
                <div class="row">
                    {!! Form::open(['route' => 'carros.store']) !!}

                        @include('carros.fields')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/carros/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Carros
        </h1>
   </section>
   <div class="content">
       @include('adminlte-templates::common.errors')
       <div class="box box-primary">
           <div class="box-body">
               <div class="row">
                   {!! Form::model($carros, ['route' => ['carros.update', $carros->id], 'method' => 'patch']) !!}

                        @include('carros.fields')

                   {!! Form::close() !!}
               </div>
           </div>
       </div>
   </div>
@endsection

resources/views/carros/fields.blade.php
<!-- Modelo Field -->
<div class="form-group col-sm-5 col-sm-offset-3">
    {!! Form::label('modelo', 'Modelo:') !!}
    {!! Form::text('modelo', null, ['class' => 'form-control']) !!}
</div>

<!-- Placa Field -->
<div class="form-group col-sm-5 col-sm-offset-3">
    {!! Form::label('placa', 'Placa:') !!}
    {!! Form::text('placa', null, ['class' => 'form-control']) !!}
</div>

@if( !isset($cedula) )
    <!-- Cliente Field -->
    <div class="form-group col-sm-5 col-sm-offset-3">
        {!! Form::label('cliente', 'Cliente:') !!}
        <select class="form-control select2" name="cliente_id">
          @foreach($clientes as $cliente)
          <option value="{{ $cliente->id }}" {{ ($cliente->id == $carros->clente_id)? 'selected=""' : '' }}>{{ $cliente->data }}</option>
          @endforeach
      </select>
    </div>
    <!-- Submit Field -->
    <div class="form-group col-sm-12">
        {!! Form::submit('Guardar', ['class' => 'btn btn-primary']) !!}
        <a href="{!! route('carros.index') !!}" class="btn btn-default">Cancelar</a>
    </div>
@endif

resources/views/carros/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1 class="pull-left">Carros</h1>
        <h1 class="pull-right">
           <a class="btn btn-primary pull-right" style="margin-top: -10px;margin-bottom: 5px" href="{!! route('carros.create') !!}">Agregar</a>
        </h1>
    </section>
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">
                    @include('carros.table')
            </div>
        </div>
    </div>
@endsection

resources/views/carros/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Carros
        </h1>
    </section>
    <div class="content">
        <div class="box box-primary">
            <div class="box-body">
                <div class="row" style="padding-left: 20px">
                    @include('carros.show_fields')
                    <a href="{!! route('carros.index') !!}" class="btn btn-default">Volver</a>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/carros/show_fields.blade.php
<!-- Id Field -->
<div class="form-group">
    {!! Form::label('id', 'Id:') !!}
    <p>{!! $carros->id !!}</p>
</div>

<!-- Modelo Field -->
<div class="form-group">
    {!! Form::label('modelo', 'Modelo:') !!}
    <p>{!! $carros->modelo !!}</p>
</div>

<!-- Placa Field -->
<div class="form-group">
    {!! Form::label('placa', 'Placa:') !!}
    <p>{!! $carros->placa !!}</p>
</div>

<!-- Cliente Field -->
<div class="form-group">
    {!! Form::label('cliente', 'Cliente:') !!}
    <p>{!! $carros->cliente->data !!}</p>
</div>

<!-- Created At Field -->
<div class="form-group">
    {!! Form::label('created_at', 'Registrado:') !!}
    <p>{!! $carros->created_at !!}</p>
</div>

<!-- Updated At Field -->
<div class="form-group">
    {!! Form::label('updated_at', 'Ultima actualización:') !!}
    <p>{!! $carros->updated_at !!}</p>
</div>

resources/views/carros/table.blade.php
<table class="table table-responsive" id="carros-table">
    <thead>
        <th>Modelo</th>
        <th>Placa</th>
        <th>Cliente</th>
        <th>Facturas</th>
        <th colspan="3">Acciones</th>
    </thead>
    <tbody>
    @foreach($carros as $carro)
        <tr>
            <td>{!! $carro->modelo !!}</td>
            <td>{!! $carro->placa !!}</td>
            <td>{!! $carro->cliente->data !!}</td>
            <td>{{ count($carro->facturas) }}</td>
            <td>
                {!! Form::open(['route' => ['carros.destroy', $carro->id], 'method' => 'delete']) !!}
                <div class='btn-group'>
                    <a href="{!! route('carros.show', [$carro->id]) !!}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-eye-open"></i></a>
                    <a href="{!! route('carros.edit', [$carro->id]) !!}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-edit"></i></a>
                    {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-danger btn-xs', 'onclick' => "return confirm('¿Está seguro?')"]) !!}
                </div>
                {!! Form::close() !!}
            </td>
        </tr>
    @endforeach
    </tbody>
</table>