routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('/home');
});

Auth::routes();
Route::middleware(['auth'])->group(function () {

	Route::get('/home', 'HomeController@index')->name('home');


	Route::resource('clientes', 'clientesController');

	Route::resource('carros', 'carrosController');

	Route::resource('servicios', 'ServicioController');

	Route::get('facturas/new/{id}', 'FacturasController@new_fac');
	Route::post('facturas/new', 'FacturasController@new_storage');
	Route::resource('facturas', 'FacturasController');

});

app/Models/Facturas.php
<?php

namespace App\Models;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Class Facturas
 * @package App\Models
 * @version May 21, 2017, 10:01 pm UTC
 */
class Facturas extends Model
{
    use SoftDeletes;

    public $table = 'facturas';
    

    protected $dates = ['deleted_at'];


    public $fillable = [
        'servicio',
        'precio',
        'carro_id'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'servicio' => 'string',
        'carro' => 'string'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        
    ];

    public function carro()
    {
        return $this->belongsTo('App\Models\carros','carro_id');
    }    

    public function getCreatedAttribute()
    {
        return \Carbon\Carbon::parse($this->created_at)->format('d/m/Y');
    }
}

app/Models/clientes.php
<?php

namespace App\Models;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Class clientes
 * @package App\Models
 * @version May 21, 2017, 9:43 pm UTC
 */
class clientes extends Model
{
    use SoftDeletes;

    public $table = 'clientes';
    

    protected $dates = ['deleted_at'];


    public $fillable = [
        'nombre',
        'apellido',
        'cedula'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'nombre' => 'string',
        'apellido' => 'string',
        'cedula' => 'string'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        'nombre' => 'required',
        'apellido' => 'required',
        'cedula' => 'required'
    ];
    
    public static function boot()
    {
        parent::boot();
    
        static::deleting(function($cliente) { 
             $cliente->carros()->delete();
        });
    }

    public function carros()
    {
        return $this->hasMany('App\Models\carros','cliente_id');
    }
    
    public function facturas()
    {

    }

    public function getDataAttribute()
    {
        return $this->cedula . '  -  ' . $this->nombre . ' ' . $this->apellido;
    }

    public function getTotalFacturasAttribute()
    {
        $total = 0;
        foreach ($this->carros as $carro) {
            $total += count($carro->facturas); 
        }
        return $total;
    }

    public function getFourPromotionAttribute()
    {
        $total_facturas = $this->getTotalFacturasAttribute();
        $total_facturas++;
        return ( fmod($total_facturas, 4) == 0 ) && $total_facturas >= 4;
    }
}

app/Http/Controllers/FacturasController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateFacturasRequest;
use App\Http\Requests\UpdateFacturasRequest;
use App\Repositories\FacturasRepository;
use App\Http\Controllers\AppBaseController;
use Illuminate\Http\Request;
use Flash;
use Prettus\Repository\Criteria\RequestCriteria;
use Response;
// Models
use App\Models\Facturas;
use App\Models\clientes;
use App\Models\carros;
use App\Models\Servicio;


class FacturasController extends AppBaseController
{
    /** @var  FacturasRepository */
    private $facturasRepository;

    public function __construct(FacturasRepository $facturasRepo)
    {
        $this->facturasRepository = $facturasRepo;
    }

    /**
     * Display a listing of the Facturas.
     *
     * @param Request $request
     * @return Response
     */
    public function index(Request $request)
    {
        $this->facturasRepository->pushCriteria(new RequestCriteria($request));
        $facturas = $this->facturasRepository->all();

        return view('facturas.index')
            ->with('facturas', $facturas);
    }

    /**
     * Show the form for creating a new Facturas.
     *
     * @return Response
     */
    public function create()
    {
        $clientes = clientes::with('carros')->orderBy('cedula','asc')->get();
        $servicios = Servicio::orderBy('nombre','asc')->get();
        return view('facturas.create')
                ->with('clientes',$clientes)
                ->with('servicios',$servicios);
    }

    /**
     * Store a newly created Facturas in storage.
     *
     * @param CreateFacturasRequest $request
     *
     * @return Response
     */
    public function store(CreateFacturasRequest $request)
    {
        $carro = carros::find( $request->carro_id );

        $cliente = $carro->cliente;

        $isPromo = $cliente->getFourPromotionAttribute();
        
        $this->save( $request->servicio, $carro->id, $isPromo );

        Flash::success('Factura registrada correctamente.');

        return redirect(route('facturas.index'));
    }

    /**
     * Display the specified Facturas.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $facturas = $this->facturasRepository->findWithoutFail($id);

        if (empty($facturas)) {
            Flash::error('Facturas not found');

            return redirect(route('facturas.index'));
        }

        return view('facturas.show')->with('facturas', $facturas);
    }

    /**
     * Show the form for editing the specified Facturas.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $facturas = $this->facturasRepository->findWithoutFail($id);

        if (empty($facturas)) {
            Flash::error('Facturas not found');

            return redirect(route('facturas.index'));
        }

        return view('facturas.edit')->with('facturas', $facturas);
    }

    /**
     * Update the specified Facturas in storage.
     *
     * @param  int              $id
     * @param UpdateFacturasRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateFacturasRequest $request)
    {
        $facturas = $this->facturasRepository->findWithoutFail($id);

        if (empty($facturas)) {
            Flash::error('Facturas not found');

            return redirect(route('facturas.index'));
        }

        $facturas = $this->facturasRepository->update($request->all(), $id);

        Flash::success('Facturas updated successfully.');

        return redirect(route('facturas.index'));
    }

    /**
     * Remove the specified Facturas from storage.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function destroy($id)
    {
        $facturas = $this->facturasRepository->findWithoutFail($id);

        if (empty($facturas)) {
            Flash::error('Facturas not found');

            return redirect(route('facturas.index'));
        }

        $this->facturasRepository->delete($id);

        Flash::success('Factura borrada correctamente.');

        return redirect(route('facturas.index'));
    }

    public function new_fac($id)
    {
        $servicios = Servicio::all();
        return view('facturas.new')
                ->with('servicios',$servicios)
                ->with('cedula',$id);
    }

    public function new_storage(Request $request)
    {
        $cliente =  new clientes();
        $cliente->fill( $request->all() )->save();

        $carro =  new carros();
        $carro->fill( $request->all() );
        $carro->cliente_id = $cliente->id;
        $carro->save();

        $this->save( $request->servicio, $carro->id, false );

        return redirect('facturas');
    }

    private function save($service_id, $carro_id, $isPromo = false)
    {
        $servicio = Servicio::find( $service_id );
        $factura =  new Facturas();
        $factura->carro_id = $carro_id;
        $factura->servicio = $servicio->nombre;
        
        $precio = $servicio->precio;
        if( $isPromo ){
            $precio /=2;
        }

        $factura->precio = $precio;
        $factura->save();
    }
}

resources/views/facturas/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Facturas
        </h1>
    </section>
    <div class="content">
        @include('adminlte-templates::common.errors')
        <div class="box box-primary">

            <div class="box-body">
                <div class="row">
                    {!! Form::open(['route' => 'facturas.store']) !!}

                        @include('facturas.fields')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/facturas/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Facturas
        </h1>
   </section>
   <div class="content">
       @include('adminlte-templates::common.errors')
       <div class="box box-primary">
           <div class="box-body">
               <div class="row">
                   {!! Form::model($facturas, ['route' => ['facturas.update', $facturas->id], 'method' => 'patch']) !!}

                        @include('facturas.fields')

                   {!! Form::close() !!}
               </div>
           </div>
       </div>
   </div>
@endsection

resources/views/facturas/fields.blade.php
<div class="offer" id="facturas-oferta">
  Esta factura se cobrara a mitad de precio gracias a la promocion
</div>
<br><br><br>
<div class="form-group col-sm-6 col-sm-offset-3">
  {!! Form::label('cliente', 'Cliente:') !!}
  <select class="form-control col-sm-6 select2" id="facturas-cliente" tabindex="1" autofocus required>
    <option></option>
    @foreach($clientes as $cliente)
      <option value="{{ $cliente->id }}" data-carros="{{ $cliente->carros }}" data-offer="{{ $cliente->four_promotion }}">{{ $cliente->data }}</option>      
    @endforeach
  </select>
</div>

<div class="form-group col-sm-6 col-sm-offset-3">
  {!! Form::label('cliente', 'Carros:') !!}
  <select class="form-control col-sm-6 select2" id="facturas-carros" name="carro_id" tabindex="2" required>
  </select>
</div>


<div class="form-group col-sm-6 col-sm-offset-3">
  {!! Form::label('servicio', 'Servicio:') !!}
  <select class="form-control col-sm-6 select2" name="servicio" tabindex="3" required>
    <option></option>
    @foreach($servicios as $servicio)
      <option value="{{ $servicio->id }}">{{ $servicio->nombre . ' - Precio: ' . $servicio->precio }}</option>
    @endforeach
  </select>
</div>

<!-- Submit Field -->
<div class="form-group col-sm-6 col-sm-offset-3">
    {!! Form::submit('Guardar', ['class' => 'btn btn-primary']) !!}
    <a href="{!! route('facturas.index') !!}" class="btn btn-default">Cancelar</a>
</div>

resources/views/facturas/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1 class="pull-left">Facturas</h1>
        <h1 class="pull-right">
           <a class="btn btn-primary pull-right" style="margin-top: -10px;margin-bottom: 5px" href="{!! route('facturas.create') !!}">Agregar</a>
        </h1>
    </section>
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">
                    @include('facturas.table')
            </div>
        </div>
    </div>
@endsection

@section('scripts')
    <script src="{{ asset('js/facturas.js') }}"></script>
@endsection

resources/views/facturas/new.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Facturas
        </h1>
    </section>
    <div class="content">
        <div class="box box-primary">
            <div class="box-body">
                <div class="row" style="padding-left: 20px">
                    <form action="/facturas/new" method="post">
                        {!! csrf_field() !!}                        
                        <legend>Cliente</legend>
                        @include('clientes.fields')

                        <legend>Carro</legend>
                        @include('carros.fields')

                        <legend>Servicio</legend>
                        <div class="form-group col-sm-6 col-sm-offset-3">
                          {!! Form::label('servicio', 'Servicio:') !!}
                          <select class="form-control col-sm-6 select2" tabindex="3" name="servicio">
                            <option></option>
                            @foreach($servicios as $servicio)
                              <option value="{{ $servicio->id }}">{{ $servicio->nombre . ' - Precio: ' . $servicio->precio }}</option>
                            @endforeach
                          </select>
                        </div>


                        <!-- Submit Field -->
                        <div class="form-group col-sm-12">
                            {!! Form::submit('Guardar', ['class' => 'btn btn-primary']) !!}
                            <a href="{!! route('facturas.create') !!}" class="btn btn-default">Cancelar</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/facturas/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Facturas
        </h1>
    </section>
    <div class="content">
        <div class="box box-primary">
            <div class="box-body">
                <div class="row" style="padding-left: 20px">
                    @include('facturas.show_fields')
                    <a href="{!! route('facturas.index') !!}" class="btn btn-default">Back</a>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/facturas/show_fields.blade.php
<!-- Id Field -->
<div class="form-group">
    {!! Form::label('id', 'Id:') !!}
    <p>{!! $facturas->id !!}</p>
</div>

<!-- Servicio Field -->
<div class="form-group">
    {!! Form::label('servicio', 'Servicio:') !!}
    <p>{!! $facturas->servicio !!}</p>
</div>

<!-- Carro Field -->
<div class="form-group">
    {!! Form::label('carro', 'Carro:') !!}
    <p>{!! $facturas->carro !!}</p>
</div>

<!-- Created At Field -->
<div class="form-group">
    {!! Form::label('created_at', 'Created At:') !!}
    <p>{!! $facturas->created_at !!}</p>
</div>

<!-- Updated At Field -->
<div class="form-group">
    {!! Form::label('updated_at', 'Updated At:') !!}
    <p>{!! $facturas->updated_at !!}</p>
</div>

resources/views/facturas/table.blade.php
<input type="text" id="date-created" class="daterange input-form" value="01/01/2015 - 01/31/2015" />

<table class="table table-responsive" id="facturas-table">
    <thead>
        <th>Fecha</th>
        <th>Servicio</th>
        <th>Precio</th>
        <th>Cedula</th>
        <th>Nombre</th>
        <th>Carro</th>
        <th>Placa</th>
        <th>Action</th>
    </thead>
    <tbody>
    @foreach($facturas as $facturas)
        <tr>
            <td>{!! $facturas->created !!}</td>
            <td>{!! $facturas->servicio !!}</td>
            <td>{!! $facturas->precio !!}</td>
            <td>{!! $facturas->carro->cliente->cedula !!}</td>
            <td>{!! $facturas->carro->cliente->nombre !!}</td>
            <td>{!! $facturas->carro->modelo !!}</td>
            <td>{!! $facturas->carro->placa !!}</td>
            <td>
                {!! Form::open(['route' => ['facturas.destroy', $facturas->id], 'method' => 'delete']) !!}
                <div class='btn-group'>
                    <a href="{!! route('facturas.show', [$facturas->id]) !!}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-eye-open"></i></a>
                    {{-- <a href="{!! route('facturas.edit', [$facturas->id]) !!}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-edit"></i></a> --}}
                    {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-danger btn-xs', 'onclick' => "return confirm('¿Está seguro?')"]) !!}
                </div>
                {!! Form::close() !!}
            </td>
        </tr>
    @endforeach
    </tbody>
</table>